---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  tasks:
    - name: install packages
      apt: name={{ item }} state=present
      with_items:
        - tmux
        - expect
        - git
        - zsh
- include: playbooks/go.yml
- include: playbooks/go_pkg.yml
#- include: vim/latest.yml
