---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  tasks:
    - name: install packages
      apt: name={{ item }} state=present
      with_items:
        - gsfonts
        - gsfonts-x11
        - fonts-dejavu-core
        - ttf-bitstream-vera
        - fonts-freefont-ttf
        - tmux
        - expect
        - git
- include: playbooks/git_config.yml
- include: playbooks/ssh_key.yml
- include: playbooks/go.yml
- include: playbooks/go_pkg.yml
#- include: playbooks/docker.yml
- include: playbooks/vim.yml
- include: playbooks/hub.yml
- include: playbooks/lein.yml
- include: playbooks/gpg.yml
- include: playbooks/zsh.yml
- include: playbooks/dotfiles.yml
