---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars:
    go_url: "http://golang.org/dl/go1.4.linux-amd64.tar.gz"
    prefix_dir: "/usr/local"
  tasks:
    - name: install mercurial
      apt: name=mercurial state=present
    - name: install tar
      apt: name=tar state=present
    - get_url: url={{go_url}} dest={{prefix_dir}}/src/go.tar.gz
    - shell: tar xvf src/go.tar.gz
      args:
        chdir: "{{prefix_dir}}"
        creates: "{{prefix_dir}}/go/bin/go"
