---
- include: java.yml
- hosts: 127.0.0.1
  connection: local
  vars:
    lein_url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  tasks:
    - file: dest=~/bin state=directory
    - get_url: url={{lein_url}} validate_certs=no dest=~/bin/lein mode=0755
    - shell: ~/bin/lein self-install
      args:
        chdir: ~/bin
        creates: ~/.lein/self-installs
