---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  tasks:
    - name: ssh key gen
      user: name={{ item }} generate_ssh_key=yes
      with_items:
        - root
        - vagrant
          #cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys
          #chmod 600 ~/.ssh/authorized_keys
