---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars:
    luajit_repo: "http://luajit.org/git/luajit-2.0.git"
    vim_repo: "https://vim.googlecode.com/hg/"
    vim_configure: "--prefix=/usr/local --with-features=huge --enable-multibyte --enable-luainterp --with-luajit --enable-fail-if-missing"
    src_dir: "/usr/local/src"
  tasks:
    - name: install packages
      apt: name={{ item }} state=present
      with_items:
        - build-essential
        - mercurial
        - gettext
        - libncurses5-dev
        - libacl1-dev
        - libgpm-dev
        - lua5.1
        - liblua5.1-0-dev
          #        - lua5.2
          #        - liblua5.2-dev
    - git: repo={{luajit_repo}}
           dest={{src_dir}}/luajit
           version=master
           accept_hostkey=yes
           update=no
    - shell: make && make install
      args:
        chdir: "{{src_dir}}/luajit"
        creates: "/usr/local/lib/libluajit-5.1.so"
    - hg: repo={{vim_repo}}
          dest={{src_dir}}/vim
    - shell: ./configure {{vim_configure}} && make && make install
      args:
        chdir: "{{src_dir}}/vim"
        creates: "/usr/local/bin/vim"
    # remove vim-mininal
    - name: remove pre-installed vim
      apt: name={{ item }} state=absent
      with_items:
        - vim-tiny
        - vim-common
        - vim-runtime
        - vim
